export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
export const LOGIN_AUTH_FAILED = 'LOGIN_AUTH_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
